name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  image: andygodish/landing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Fetch all tags
      run: git fetch --tags

    - name: Set semantic version as env variable
      run: |
        SEM_VER=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "SEM_VER=$SEM_VER" >> $GITHUB_ENV

    - name: Build image
      run: docker build -t ${{ env.image }}:${{ env.SEM_VER }} .

    - name: Tag Latest
      run : docker tag ${{ env.image }}:${{ env.SEM_VER }} ${{ env.image }}:latest

    - name: Push image
      run: |
        docker push ${{ env.image }}:${{ env.SEM_VER }}
        docker push ${{ env.image }}:latest