name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

# Before this was added, I was getting this error:
# Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under
# '/home/runner/work/golang-demoapp/golang-demoapp/.github/actions/golang/action.yaml'.
# Did you forget to run actions/checkout before running your local action?
permissions:
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20.11'
        registry-url: 'https://registry.npmjs.org'

    - name: Install npm packages
      run: npm install -y

    - name: Execute Unit Tests
      run: npm test

    - name: Semantic release
      uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        force-bump-patch-version: true
        update-file: "./package.json"

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Bumped version in package.json"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}