name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: choice
        options:
          - 'v1.0.1'
          - 'v1.0.0' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Azure CLI version
      run: az --version

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Set up Docker container
    #   run: |
    #     # Your deployment commands to Azure using the selected version
    #     # This might include pulling the Docker image tagged with the selected version
    #     # and deploying it to the Azure Web App
