name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: choice
        options:
          - 'v1.0.5'
          - 'v1.0.4'
          - 'v1.0.3'
          - 'v1.0.2'
          - 'v1.0.1'
          - 'v1.0.0' 
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - name: Check Azure CLI version
      run: az --version

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az webapp config container set \
            --name as-agio-land-prod-wus \
            --resource-group rg-agio-land-prod-wus \
            --docker-custom-image-name andygodish/landing:${{ github.event.inputs.version }}

