name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - ".github/**"
      - "**.json"
      - "manifests/**"
      - "scripts/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - ".github/**"
      - "**.json"
      - "manifests/**"
      - "scripts/**"

permissions:
  contents: write

env:
  image: andygodish/landing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
          registry-url: "https://registry.npmjs.org"

      - name: Install npm packages
        run: npm install -y

      - name: Execute Unit Tests
        run: npm test
  
  version:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
          registry-url: "https://registry.npmjs.org"

      - name: Semantic release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
          update-file: "./package.json"

      - name: Update deploy-production.yaml workflow with new version and Save Version
        id: set_version
        run: |
          VERSION=v$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          sed -i '/options:/a \          - '"'$VERSION'"'' .github/workflows/deploy-production.yaml

      - name: Commit files
        run: |
          git config --local user.email "agodish18@gmail.com"
          git config --local user.name "Andy Godish"
          git commit -a -m "Bumped version in package.json, added VERSION to input list in deploy workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref }}

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          VERSION=${{ needs.version.outputs.version }}
          docker build -t ${{ env.image }}:$VERSION .
          docker tag ${{ env.image }}:$VERSION ${{ env.image }}:latest
          docker push ${{ env.image }}:$VERSION
          docker push ${{ env.image }}:latest

  deploy-staging:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [version, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update deployment image tag
        run: sh ./scripts/update-tag.sh ${{ needs.version.outputs.version }}

      - name: Commit changes
        run: |
          git config --local user.email "agodish18@gmail.com"
          git config --local user.name "Andy Godish"
          git pull -r
          git commit -a -m "Bumped version image tag in manifests/staging/deployment.yaml"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref }}